/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cars24;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.getString;

/**
 *
 * @author admin
 */
public class bill extends javax.swing.JFrame {
Toolkit tk = Toolkit.getDefaultToolkit();
int xsize=(int)tk.getScreenSize().getWidth();
int ysize=(int)tk.getScreenSize().getHeight();
    /**
     * Creates new form bill
     */
    public bill() {
        initComponents();
        jPanel1.setFocusable(true);
        this.setSize(xsize, ysize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        brand = new javax.swing.JLabel();
        model = new javax.swing.JLabel();
        regno = new javax.swing.JLabel();
        cname = new javax.swing.JLabel();
        cgst = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        email = new javax.swing.JLabel();
        color = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        pno = new javax.swing.JLabel();
        sgst = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        reg = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.setLayout(null);

        brand.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jPanel1.add(brand);
        brand.setBounds(430, 430, 160, 30);

        model.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jPanel1.add(model);
        model.setBounds(430, 470, 160, 30);

        regno.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jPanel1.add(regno);
        regno.setBounds(430, 510, 200, 30);

        cname.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jPanel1.add(cname);
        cname.setBounds(210, 200, 140, 40);

        cgst.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jPanel1.add(cgst);
        cgst.setBounds(1140, 504, 140, 40);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton2.setText("Back");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1340, 30, 69, 15);

        email.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jPanel1.add(email);
        email.setBounds(210, 250, 450, 40);

        color.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jPanel1.add(color);
        color.setBounds(430, 590, 160, 30);

        year.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jPanel1.add(year);
        year.setBounds(430, 550, 150, 30);

        pno.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jPanel1.add(pno);
        pno.setBounds(210, 300, 190, 40);

        sgst.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jPanel1.add(sgst);
        sgst.setBounds(1140, 450, 150, 40);

        price.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jPanel1.add(price);
        price.setBounds(1140, 400, 140, 40);

        total.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jPanel1.add(total);
        total.setBounds(1140, 560, 140, 40);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("INVOICE");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(660, 50, 160, 43);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("CUSTOMER DETAILS");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(200, 140, 260, 29);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("CAR DETAILS");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(320, 370, 220, 29);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel4.setText("BRAND :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(300, 430, 100, 26);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel5.setText("MODEL :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(300, 470, 100, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel6.setText("REG. NO. :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(290, 510, 120, 26);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel7.setText("COLOR :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(310, 590, 100, 26);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel8.setText("YEAR :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(330, 550, 90, 26);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel9.setText("PRICE OF CAR");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(910, 410, 160, 26);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel10.setText("C.GST (9%)");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(940, 510, 130, 26);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel11.setText("S.GST (9%)");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(940, 460, 120, 20);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel12.setText("TOTAL");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(960, 570, 110, 35);

        reg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regActionPerformed(evt);
            }
        });
        jPanel1.add(reg);
        reg.setBounds(930, 190, 150, 40);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jButton1.setText("Evaluate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1160, 190, 110, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1540, 870);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String sql ="select brand,model,regno,regyear,color,bid,pno from cardatabase where regno=?";
        String sql1 ="select fname,lname,email,pno from logintable where pno=?";
        String sql2="update cardatabase set sold=1 where regno=?";
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/loginandregister","root","bms@ise");
            
            PreparedStatement pstmt =conn.prepareStatement(sql);
            
            pstmt.setString(1,reg.getText());
            ResultSet rs=pstmt.executeQuery();
            
            if(rs.next())
            {
                if(Integer.parseInt(rs.getString(6))==0)
                {
                    JOptionPane.showMessageDialog(null,"There is no bid on this car");
                    return;
                }
                else
                {
                brand.setText(rs.getString(1));
                model.setText(rs.getString(2));
                regno.setText(rs.getString(3));
                year.setText(rs.getString(4));
                color.setText(rs.getString(5));
                price.setText(rs.getString(6));
                double x,y;
                x = (double) (Double.parseDouble(rs.getString(6))*0.09);
                cgst.setText(Double.toString(x));
                sgst.setText(Double.toString(x));
                y=(Double.parseDouble(rs.getString(6))+x+x);
                total.setText(Double.toString(y));
                }
            }
            PreparedStatement pstmt1 =conn.prepareStatement(sql1);
            pstmt1.setString(1,rs.getString(7));
            ResultSet rs1=pstmt1.executeQuery();
            if(rs1.next())
            {
                if(Integer.parseInt(rs.getString(6))==0)
                {
                JOptionPane.showMessageDialog(null,"There is no bid on this car");
                return;
                }
                else
                {
            cname.setText(rs1.getString(1)+" "+rs1.getString(2));
            
            email.setText(rs1.getString(3));
            pno.setText(rs1.getString(4));
                }
            
            }
            PreparedStatement pstmt2 =conn.prepareStatement(sql2);
            if(Integer.parseInt(rs.getString(6))==0)
            {
                JOptionPane.showMessageDialog(null,"There is no bid on this car");
                return;
            }
            else
            {
            pstmt2.setString(1,rs.getString(3));
            pstmt2.executeUpdate();
                String to = email.getText();
                System.out.println(email.getText());
                String subject = "regarding car bidding";
                String message =  "Congrats you can take the car from the showroom";
                
                String user = "cars24.dbms.java@gmail.com";
                String pass = "dbmsjava";

                SendMail.send(to,subject, message, user, pass);
            }
            
            conn.close();

        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new assignsell().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brand;
    private javax.swing.JLabel cgst;
    private javax.swing.JLabel cname;
    private javax.swing.JLabel color;
    private javax.swing.JLabel email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel model;
    private javax.swing.JLabel pno;
    private javax.swing.JLabel price;
    private javax.swing.JTextField reg;
    private javax.swing.JLabel regno;
    private javax.swing.JLabel sgst;
    private javax.swing.JLabel total;
    private javax.swing.JLabel year;
    // End of variables declaration//GEN-END:variables
}
