/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cars24;
import java.awt.Color;
import java.awt.Toolkit;
import java.net.Authenticator;
import java.sql.*;

import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import javax.mail.Session;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author hruth
 */

public class buyer extends javax.swing.JFrame {
String p;
String z;
String y;
String s;
String e;
Toolkit tk = Toolkit.getDefaultToolkit();
int xsize=(int)tk.getScreenSize().getWidth();
int ysize=(int)tk.getScreenSize().getHeight();


    @Override
    public void setSize(int width, int height) {
        super.setSize(width, height); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * Creates new form buyer
     */
    
    public buyer() {
        initComponents();
        jPanel1.setFocusable(true);
    }
    public buyer(String x,String m,String e1) 
    {
       initComponents();
        jPanel1.setFocusable(true);
        p=m;
        y=x;
        z="Hey, "+x;
        name1.setText(z);
        this.setSize(xsize, ysize);
        e=e1;
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        search = new javax.swing.JButton();
        base = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        bidx = new javax.swing.JTextField();
        model1 = new javax.swing.JTextField();
        color = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        brand = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        name1 = new javax.swing.JLabel();
        reg = new javax.swing.JLabel();
        bid = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hbid = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(446, 543));
        jPanel1.setLayout(null);

        search.setBackground(new java.awt.Color(0, 153, 255));
        search.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search");
        search.setBorder(null);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search);
        search.setBounds(650, 310, 106, 40);

        base.setBackground(new java.awt.Color(255, 255, 255));
        base.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        base.setOpaque(true);
        jPanel1.add(base);
        base.setBounds(440, 650, 150, 37);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Base Price");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(470, 690, 70, 23);

        tab.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tab.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(350, 440, 780, 150);

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setText("Logout");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(1310, 150, 73, 36);

        bidx.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jPanel1.add(bidx);
        bidx.setBounds(780, 650, 120, 40);

        model1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        model1.setForeground(new java.awt.Color(102, 102, 102));
        model1.setText("Model");
        model1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                model1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                model1FocusLost(evt);
            }
        });
        model1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                model1KeyPressed(evt);
            }
        });
        jPanel1.add(model1);
        model1.setBounds(350, 310, 180, 50);

        color.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        color.setForeground(new java.awt.Color(102, 102, 102));
        color.setText("Color");
        color.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                colorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                colorFocusLost(evt);
            }
        });
        color.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                colorKeyPressed(evt);
            }
        });
        jPanel1.add(color);
        color.setBounds(350, 370, 180, 50);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Find your dream car here...");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(400, 140, 460, 80);

        brand.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        brand.setForeground(new java.awt.Color(102, 102, 102));
        brand.setText("Brand");
        brand.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        brand.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                brandFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                brandFocusLost(evt);
            }
        });
        brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandActionPerformed(evt);
            }
        });
        brand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                brandKeyPressed(evt);
            }
        });
        jPanel1.add(brand);
        brand.setBounds(350, 250, 180, 50);

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(640, 740, 139, 36);

        name1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(name1);
        name1.setBounds(1090, 80, 280, 60);

        reg.setBackground(new java.awt.Color(255, 255, 255));
        reg.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        reg.setOpaque(true);
        jPanel1.add(reg);
        reg.setBounds(260, 650, 160, 37);

        bid.setBackground(new java.awt.Color(0, 153, 255));
        bid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bid.setForeground(new java.awt.Color(255, 255, 255));
        bid.setText("Bid");
        bid.setBorder(null);
        bid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bidActionPerformed(evt);
            }
        });
        jPanel1.add(bid);
        bid.setBounds(950, 650, 139, 37);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Your Bid");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(810, 690, 60, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Reg no.");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(310, 690, 60, 23);

        hbid.setBackground(new java.awt.Color(255, 255, 255));
        hbid.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        hbid.setOpaque(true);
        jPanel1.add(hbid);
        hbid.setBounds(610, 650, 150, 37);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Current Highest bid");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(620, 690, 130, 23);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars24/1.png"))); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(1536, 864));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 1536, 860);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1536, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bidActionPerformed
        String sql1 ="select bid,assigned,email from cardatabase where regno=?";
        String sql ="update cardatabase set bid=?,pno=?,email=? where regno=?";
        
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/loginandregister","root","bms@ise");
            PreparedStatement pstmt =conn.prepareStatement(sql);
            PreparedStatement pstmt1 =conn.prepareStatement(sql1);
            pstmt1.setString(1,reg.getText());
            
            ResultSet x = pstmt1.executeQuery();
            
            if(x.next())
            {
                
                if(Double.parseDouble(x.getString(1))<Double.parseDouble(bidx.getText()) && (Double.parseDouble(x.getString(2))<Double.parseDouble(bidx.getText())))
                {
                    pstmt.setString(1,bidx.getText());
                    pstmt.setString(2,p);
                    pstmt.setString(3,e);
                    
                    pstmt.setString(4,reg.getText());
                    pstmt.executeUpdate();
                    //SendMail.send("hruthwik.krishnamurthy11@gmail.com","bidding","Someone bid more than your value on the car","cars24.dbms.java@gmail.com","dbmsjava");
                    JOptionPane.showMessageDialog(null,"Bid sucessfull. ");
                    /*String to = x.getString(3);
                String subject = "regarding bidding";
                String message =  "Sorry someone bid more than yours";
                
                String user = "cars24.dbms.java@gmail.com";
                String pass = "dbmsjava";

                SendMail.send(to,subject, message, user, pass);*/

                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Your Bid is too Low");
                }
            }
            
            conn.close();

        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);

        }
    }//GEN-LAST:event_bidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new buysell(y,p,e).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void brandKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brandKeyPressed
        int key=evt.getKeyCode();
        if(key==10)
        {
            model1.requestFocus();
        }
    }//GEN-LAST:event_brandKeyPressed

    private void brandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandActionPerformed

    private void brandFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_brandFocusLost
        if(brand.getText().trim().equals("") || brand.getText().trim().toLowerCase().equals("brand")){
            brand.setText("Brand");
            brand.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_brandFocusLost

    private void brandFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_brandFocusGained
        if(brand.getText().trim().toLowerCase().equals("brand"))
        {
            brand.setText("");
            brand.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_brandFocusGained

    private void colorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_colorKeyPressed
        int key=evt.getKeyCode();
        if(key==10)
        {
            try
            {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/loginandregister","root","bms@ise");
            String sql="select brand,model,regyear,color,km,location,regno,variant,assigned,bid from cardatabase where accept=1 and (brand= ? and (model= ? or (color= ?)))";

            PreparedStatement pstmt =conn.prepareStatement(sql);
            pstmt.setString(1,brand.getText());
            pstmt.setString(2,model1.getText());
            pstmt.setString(3,color.getText());

            ResultSet rs = pstmt.executeQuery();
            tab.setModel(DbUtils.resultSetToTableModel(rs));
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_colorKeyPressed

    private void colorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_colorFocusLost
        if(color.getText().trim().equals("") || color.getText().trim().toLowerCase().equals("color")){
            color.setText("Color");
            color.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_colorFocusLost

    private void colorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_colorFocusGained
        if(color.getText().trim().toLowerCase().equals("color"))
        {
            color.setText("");
            color.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_colorFocusGained

    private void model1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_model1KeyPressed
        int key=evt.getKeyCode();
        if(key==10)
        {
            color.requestFocus();
        }
    }//GEN-LAST:event_model1KeyPressed

    private void model1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_model1FocusLost
        if(model1.getText().trim().equals("") || model1.getText().trim().toLowerCase().equals("model")){
            model1.setText("Model");
            model1.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_model1FocusLost

    private void model1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_model1FocusGained
        if(model1.getText().trim().toLowerCase().equals("model"))
        {
            model1.setText("");
            model1.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_model1FocusGained

    private void tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMouseClicked
        DefaultTableModel model = (DefaultTableModel)tab.getModel();

        int selectedRowIndex = tab.getSelectedRow();

        reg.setText(model.getValueAt(selectedRowIndex, 7).toString());
        hbid.setText(model.getValueAt(selectedRowIndex, 10).toString());
        base.setText(model.getValueAt(selectedRowIndex, 9).toString());
        //s = model.getValueAt(selectedRowIndex, 5).toString();
    }//GEN-LAST:event_tabMouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/loginandregister","root","bms@ise");
            String sql="select brand,model,regyear,color,km,des,location,regno,variant,assigned,bid from cardatabase where accept=1 and (brand= ? and (model= ? or (color= ?)))";

            PreparedStatement pstmt =conn.prepareStatement(sql);
            pstmt.setString(1,brand.getText());
            pstmt.setString(2,model1.getText());
            pstmt.setString(3,color.getText());

            ResultSet rs = pstmt.executeQuery();
             tab.setModel(DbUtils.resultSetToTableModel(rs));
            if(rs.next()==false &&tab.getRowCount()==0)
            {
                JOptionPane.showMessageDialog(null,"NO details found");
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_searchActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new homepage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buyer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel base;
    private javax.swing.JButton bid;
    private javax.swing.JTextField bidx;
    private javax.swing.JTextField brand;
    private javax.swing.JTextField color;
    private javax.swing.JLabel hbid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField model1;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel reg;
    private javax.swing.JButton search;
    private javax.swing.JTable tab;
    // End of variables declaration//GEN-END:variables
}
