/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cars24;

import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
/**
 *
 * @author hruth
 */
public class sellerdetails extends javax.swing.JFrame {
String p;
String z;
String y;
String e;
Toolkit tk = Toolkit.getDefaultToolkit();
int xsize=(int)tk.getScreenSize().getWidth();
int ysize=(int)tk.getScreenSize().getHeight();

    @Override
    public void setSize(int width, int height) {
        super.setSize(width, height); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * Creates new form sellerdetails
     */
    public sellerdetails() {
        initComponents();
        jPanel1.setFocusable(true);
        this.setSize(xsize, ysize);
    }
    public sellerdetails(String x,String m,String e1) {
        initComponents();
        jPanel1.setFocusable(true);
        p=m;
        y=x;
        z="Hey, "+y;
        name1.setText(z);
        this.setSize(xsize, ysize);
        e=e1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        name1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        namea = new javax.swing.JTextField();
        addr = new javax.swing.JTextField();
        accno = new javax.swing.JTextField();
        ifsc = new javax.swing.JTextField();
        bnk = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("Enter your account details");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(530, 30, 420, 50);

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setText("Logout");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(1270, 140, 73, 36);

        name1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(name1);
        name1.setBounds(1090, 80, 280, 60);

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(700, 640, 100, 36);

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(650, 560, 201, 41);

        namea.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        namea.setForeground(new java.awt.Color(102, 102, 102));
        namea.setText("Name of the account holder");
        namea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameaFocusLost(evt);
            }
        });
        namea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameaActionPerformed(evt);
            }
        });
        namea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameaKeyPressed(evt);
            }
        });
        jPanel1.add(namea);
        namea.setBounds(640, 110, 220, 60);

        addr.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        addr.setForeground(new java.awt.Color(102, 102, 102));
        addr.setText("Branch Address");
        addr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addrFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addrFocusLost(evt);
            }
        });
        addr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrActionPerformed(evt);
            }
        });
        jPanel1.add(addr);
        addr.setBounds(640, 460, 220, 60);

        accno.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        accno.setForeground(new java.awt.Color(102, 102, 102));
        accno.setText("Account Number");
        accno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                accnoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                accnoFocusLost(evt);
            }
        });
        accno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accnoActionPerformed(evt);
            }
        });
        accno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                accnoKeyPressed(evt);
            }
        });
        jPanel1.add(accno);
        accno.setBounds(640, 210, 220, 60);

        ifsc.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ifsc.setForeground(new java.awt.Color(102, 102, 102));
        ifsc.setText("IFSC Code");
        ifsc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ifscFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ifscFocusLost(evt);
            }
        });
        ifsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ifscActionPerformed(evt);
            }
        });
        ifsc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ifscKeyPressed(evt);
            }
        });
        jPanel1.add(ifsc);
        ifsc.setBounds(640, 290, 220, 60);

        bnk.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bnk.setForeground(new java.awt.Color(102, 102, 102));
        bnk.setText("Name of the bank");
        bnk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bnkFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bnkFocusLost(evt);
            }
        });
        bnk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnkActionPerformed(evt);
            }
        });
        bnk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bnkKeyPressed(evt);
            }
        });
        jPanel1.add(bnk);
        bnk.setBounds(640, 380, 220, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars24/1.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1530, 860);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1540, 870);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameaActionPerformed

    private void nameaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameaFocusGained
        if(namea.getText().trim().toLowerCase().equals("name of the account holder"))
        {
            namea.setText("");
            namea.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_nameaFocusGained

    private void nameaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameaFocusLost
        if(namea.getText().trim().equals("") || namea.getText().trim().toLowerCase().equals("name of the account holder")){
            namea.setText("Name of the account holder");
            namea.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_nameaFocusLost

    private void addrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addrFocusGained
        if(addr.getText().trim().toLowerCase().equals("branch address"))
        {
            addr.setText("");
            addr.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_addrFocusGained

    private void addrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addrFocusLost
        if(addr.getText().trim().equals("") || addr.getText().trim().toLowerCase().equals("branch address")){
            addr.setText("Branch Address");
            addr.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_addrFocusLost

    private void addrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addrActionPerformed

    private void accnoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_accnoFocusGained
        if(accno.getText().trim().toLowerCase().equals("account number"))
        {
            accno.setText("");
            accno.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_accnoFocusGained

    private void accnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_accnoFocusLost
        if(accno.getText().trim().equals("") || accno.getText().trim().toLowerCase().equals("account number")){
            accno.setText("Account Number");
            accno.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_accnoFocusLost

    private void accnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accnoActionPerformed

    private void ifscFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ifscFocusGained
        if(ifsc.getText().trim().toLowerCase().equals("ifsc code"))
        {
            ifsc.setText("");
            ifsc.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_ifscFocusGained

    private void ifscFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ifscFocusLost
        if(ifsc.getText().trim().equals("") || ifsc.getText().trim().toLowerCase().equals("ifsc code")){
            ifsc.setText("Ifsc Code");
            ifsc.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_ifscFocusLost

    private void ifscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ifscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ifscActionPerformed

    private void bnkFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bnkFocusGained
        if(bnk.getText().trim().toLowerCase().equals("name of the bank"))
        {
            bnk.setText("");
            bnk.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_bnkFocusGained

    private void bnkFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bnkFocusLost
        if(bnk.getText().trim().equals("") || bnk.getText().trim().toLowerCase().equals("name of the bank")){
            bnk.setText("Name of the bank");
            bnk.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_bnkFocusLost

    private void bnkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnkActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String sql ="insert into sellerdetails values(?,?,?,?,?,?)";
        

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/loginandregister","root","bms@ise");
            PreparedStatement pstmt =conn.prepareStatement(sql);
            pstmt.setString(1,namea.getText());
            pstmt.setString(2,accno.getText());
            pstmt.setString(3,ifsc.getText());
            pstmt.setString(4,bnk.getText());
            pstmt.setString(5,addr.getText());
            pstmt.setString(6,p);
            
            
                
                pstmt.executeUpdate();

               
                JOptionPane.showMessageDialog(null,"Thank you, the amount will be transferred soon to your account.");

                conn.close();
            
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new buysell(y,p,e).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new homepage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nameaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameaKeyPressed
        int key=evt.getKeyCode();
        if(key==10)
        {
            accno.requestFocus();
        }
    }//GEN-LAST:event_nameaKeyPressed

    private void accnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accnoKeyPressed
        int key=evt.getKeyCode();
        if(key==10)
        {
            ifsc.requestFocus();
        }
    }//GEN-LAST:event_accnoKeyPressed

    private void ifscKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ifscKeyPressed
        int key=evt.getKeyCode();
        if(key==10)
        {
            bnk.requestFocus();
        }
    }//GEN-LAST:event_ifscKeyPressed

    private void bnkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bnkKeyPressed
        int key=evt.getKeyCode();
        if(key==10)
        {
            addr.requestFocus();
        }
    }//GEN-LAST:event_bnkKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sellerdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sellerdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sellerdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sellerdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sellerdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accno;
    private javax.swing.JTextField addr;
    private javax.swing.JTextField bnk;
    private javax.swing.JTextField ifsc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name1;
    private javax.swing.JTextField namea;
    // End of variables declaration//GEN-END:variables
}
