package cars24;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hruth
 */
public class seller extends javax.swing.JFrame {
String p;
String z;
String y;
String e;
Toolkit tk = Toolkit.getDefaultToolkit();
int xsize=(int)tk.getScreenSize().getWidth();
int ysize=(int)tk.getScreenSize().getHeight();


    @Override
    public void setSize(int width, int height) {
        super.setSize(width, height); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * Creates new form seller
     */
    public seller() {
        initComponents();
        jPanel1.setFocusable(true);
    }
    
    public seller(String x,String m,String e1) {
        initComponents();
        jPanel1.setFocusable(true);
        p=m;
        y=x;
        z="Hey, "+y;
        name1.setText(z);
        this.setSize(xsize, ysize);
        e=e1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        brand = new javax.swing.JTextField();
        model = new javax.swing.JTextField();
        regyear = new javax.swing.JTextField();
        km = new javax.swing.JTextField();
        color = new javax.swing.JTextField();
        regno = new javax.swing.JTextField();
        location = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        desc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        name1 = new javax.swing.JLabel();
        variant = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(446, 543));
        jPanel1.setLayout(null);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("Logout");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(1310, 150, 73, 36);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Sell your car...");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(700, 200, 230, 49);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Enter your car details below");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(620, 270, 310, 36);

        brand.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        brand.setForeground(new java.awt.Color(102, 102, 102));
        brand.setText("Brand");
        brand.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                brandFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                brandFocusLost(evt);
            }
        });
        brand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                brandKeyPressed(evt);
            }
        });
        jPanel1.add(brand);
        brand.setBounds(610, 330, 150, 37);

        model.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        model.setForeground(new java.awt.Color(102, 102, 102));
        model.setText("Model");
        model.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                modelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                modelFocusLost(evt);
            }
        });
        model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelActionPerformed(evt);
            }
        });
        model.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                modelKeyPressed(evt);
            }
        });
        jPanel1.add(model);
        model.setBounds(830, 330, 140, 37);

        regyear.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        regyear.setForeground(new java.awt.Color(102, 102, 102));
        regyear.setText("Registration Year");
        regyear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                regyearFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                regyearFocusLost(evt);
            }
        });
        regyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regyearActionPerformed(evt);
            }
        });
        regyear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                regyearKeyPressed(evt);
            }
        });
        jPanel1.add(regyear);
        regyear.setBounds(610, 380, 150, 37);

        km.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        km.setForeground(new java.awt.Color(102, 102, 102));
        km.setText("Km Driven");
        km.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                kmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                kmFocusLost(evt);
            }
        });
        km.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kmActionPerformed(evt);
            }
        });
        km.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kmKeyPressed(evt);
            }
        });
        jPanel1.add(km);
        km.setBounds(610, 430, 150, 37);

        color.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        color.setForeground(new java.awt.Color(102, 102, 102));
        color.setText("Color");
        color.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                colorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                colorFocusLost(evt);
            }
        });
        color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorActionPerformed(evt);
            }
        });
        color.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                colorKeyPressed(evt);
            }
        });
        jPanel1.add(color);
        color.setBounds(830, 380, 140, 37);

        regno.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        regno.setForeground(new java.awt.Color(102, 102, 102));
        regno.setText("Reg no.");
        regno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                regnoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                regnoFocusLost(evt);
            }
        });
        regno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regnoActionPerformed(evt);
            }
        });
        regno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                regnoKeyPressed(evt);
            }
        });
        jPanel1.add(regno);
        regno.setBounds(610, 480, 150, 37);

        location.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        location.setForeground(new java.awt.Color(102, 102, 102));
        location.setText("Location");
        location.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                locationFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                locationFocusLost(evt);
            }
        });
        location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationActionPerformed(evt);
            }
        });
        location.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                locationKeyPressed(evt);
            }
        });
        jPanel1.add(location);
        location.setBounds(830, 430, 140, 37);

        price.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        price.setForeground(new java.awt.Color(102, 102, 102));
        price.setText("Price(expected)");
        price.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                priceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                priceFocusLost(evt);
            }
        });
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                priceKeyPressed(evt);
            }
        });
        jPanel1.add(price);
        price.setBounds(830, 530, 140, 37);

        desc.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        desc.setForeground(new java.awt.Color(102, 102, 102));
        desc.setText("Description");
        desc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                descFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                descFocusLost(evt);
            }
        });
        desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descActionPerformed(evt);
            }
        });
        desc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                descKeyPressed(evt);
            }
        });
        jPanel1.add(desc);
        desc.setBounds(610, 530, 191, 37);

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Submit");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(690, 590, 201, 41);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(750, 640, 69, 17);

        name1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(name1);
        name1.setBounds(1090, 90, 280, 50);

        variant.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        variant.setForeground(new java.awt.Color(102, 102, 102));
        variant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Variant", "Petrol", "Diesel" }));
        variant.setBorder(brand.getBorder());
        variant.setOpaque(false);
        jPanel1.add(variant);
        variant.setBounds(830, 480, 155, 37);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars24/1.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 1560, 870);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1570, 870);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelActionPerformed

    private void regyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regyearActionPerformed

    private void kmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kmActionPerformed

    private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorActionPerformed

    private void regnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regnoActionPerformed

    private void locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String sql ="insert into cardatabase values(?,?,?,?,?,?,?,?,?,?,0,0,null,?,0,0,0)";
        String sql1="insert into selleractivity values(?,?,?,?,?)";

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/loginandregister","root","bms@ise");
            PreparedStatement pstmt =conn.prepareStatement(sql);
            pstmt.setString(1,brand.getText());
            pstmt.setString(2,model.getText());
            pstmt.setString(3,regyear.getText());
            pstmt.setString(4,color.getText());
            pstmt.setString(5,km.getText());
            pstmt.setString(6,location.getText());
            pstmt.setString(7,regno.getText());
            if(variant.getSelectedItem().toString()=="Select Variant")
            {
                JOptionPane.showMessageDialog(null,"Select Variant");
            }
            else
            {
            pstmt.setString(8,variant.getSelectedItem().toString());
            pstmt.setString(9,desc.getText());
            pstmt.setString(10,price.getText());
            pstmt.setString(11,p);
            pstmt.executeUpdate();
            
            PreparedStatement pstmt1 =conn.prepareStatement(sql1);
            pstmt1.setString(1,p);
            pstmt1.setString(2,brand.getText());
            pstmt1.setString(3,model.getText());
            pstmt1.setString(4,regno.getText());
            
            pstmt1.setInt(5,0);
            pstmt1.executeUpdate();
            JOptionPane.showMessageDialog(null,"Congrats Now your car details is with us");
            new buysell(y,p,e).setVisible(true);
            this.setVisible(false);
            
            conn.close();
            }
        }

        catch(HeadlessException | ClassNotFoundException | SQLException e){
            String s="com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '"+regno.getText()+"' for key 'PRIMARY'";
            if(e.toString().equals(s))
            {
                JOptionPane.showMessageDialog(null,"The car with the same registration number already exists");
            }
            
            else
            {
            JOptionPane.showMessageDialog(null,"Oops... Something Happened..   Check if you have entered all the Details correctly.");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void brandFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_brandFocusGained
        if(brand.getText().trim().toLowerCase().equals("brand"))
        {
            brand.setText("");
            brand.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_brandFocusGained

    private void brandFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_brandFocusLost
        if(brand.getText().trim().equals("") || brand.getText().trim().toLowerCase().equals("brand")){
            brand.setText("Brand");
            brand.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_brandFocusLost

    private void modelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_modelFocusGained
        if(model.getText().trim().toLowerCase().equals("model"))
        {
            model.setText("");
            model.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_modelFocusGained

    private void modelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_modelFocusLost
        if(model.getText().trim().equals("") || model.getText().trim().toLowerCase().equals("model")){
            model.setText("Model");
            model.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_modelFocusLost

    private void regyearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regyearFocusGained
       if(regyear.getText().trim().toLowerCase().equals("registration year"))
        {
            regyear.setText("");
            regyear.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_regyearFocusGained

    private void regyearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regyearFocusLost
        if(regyear.getText().trim().equals("") || regyear.getText().trim().toLowerCase().equals("registration year")){
            regyear.setText("Registration Year");
            regyear.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_regyearFocusLost

    private void colorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_colorFocusGained
        if(color.getText().trim().toLowerCase().equals("color"))
        {
            color.setText("");
            color.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_colorFocusGained

    private void colorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_colorFocusLost
        if(color.getText().trim().equals("") || color.getText().trim().toLowerCase().equals("color")){
            color.setText("Color");
            color.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_colorFocusLost

    private void kmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kmFocusGained
        if(km.getText().trim().toLowerCase().equals("km driven"))
        {
            km.setText("");
            km.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_kmFocusGained

    private void kmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kmFocusLost
        if(km.getText().trim().equals("") || km.getText().trim().toLowerCase().equals("km driven")){
            km.setText("Km driven");
            km.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_kmFocusLost

    private void locationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_locationFocusGained
        if(location.getText().trim().toLowerCase().equals("location"))
        {
            location.setText("");
            location.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_locationFocusGained

    private void locationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_locationFocusLost
        if(location.getText().trim().equals("") || location.getText().trim().toLowerCase().equals("location")){
            location.setText("Location");
            location.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_locationFocusLost

    private void regnoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regnoFocusGained
        if(regno.getText().trim().toLowerCase().equals("reg no."))
        {
            regno.setText("");
            regno.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_regnoFocusGained

    private void regnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regnoFocusLost
        if(regno.getText().trim().equals("") || regno.getText().trim().toLowerCase().equals("reg no.")){
            regno.setText("Reg no.");
            regno.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_regnoFocusLost

    private void descFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descFocusGained
       if(desc.getText().trim().toLowerCase().equals("description"))
        {
            desc.setText("");
            desc.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_descFocusGained

    private void descFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descFocusLost
        if(desc.getText().trim().equals("") || desc.getText().trim().toLowerCase().equals("description")){
            desc.setText("Description");
            desc.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_descFocusLost

    private void priceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_priceFocusGained
        if(price.getText().trim().toLowerCase().equals("price(expected)"))
        {
            price.setText("");
            price.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_priceFocusGained

    private void priceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_priceFocusLost
        if(price.getText().trim().equals("") || price.getText().trim().toLowerCase().equals("price(expected)")){
            price.setText("Price(expected)");
            price.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_priceFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new buysell(y,p,e).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void brandKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brandKeyPressed
        int key=evt.getKeyCode();
        if(key==10)
        {
            model.requestFocus();
        }
    }//GEN-LAST:event_brandKeyPressed

    private void modelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modelKeyPressed
        int key=evt.getKeyCode();
        if(key==10)
        {
            regyear.requestFocus();
        }
    }//GEN-LAST:event_modelKeyPressed

    private void regyearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regyearKeyPressed
        int key=evt.getKeyCode();
        if(key==10)
        {
            color.requestFocus();
        }
    }//GEN-LAST:event_regyearKeyPressed

    private void colorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_colorKeyPressed
        int key=evt.getKeyCode();
        if(key==10)
        {
            km.requestFocus();
        }
    }//GEN-LAST:event_colorKeyPressed

    private void kmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kmKeyPressed
        int key=evt.getKeyCode();
        if(key==10)
        {
            location.requestFocus();
        }
    }//GEN-LAST:event_kmKeyPressed

    private void locationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_locationKeyPressed
        int key=evt.getKeyCode();
        if(key==10)
        {
            regno.requestFocus();
        }
    }//GEN-LAST:event_locationKeyPressed

    private void regnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regnoKeyPressed
        int key=evt.getKeyCode();
        if(key==10)
        {
            variant.requestFocus();
        }
    }//GEN-LAST:event_regnoKeyPressed

    private void descKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descKeyPressed
        int key=evt.getKeyCode();
        if(key==10)
        {
            price.requestFocus();
        }
    }//GEN-LAST:event_descKeyPressed

    private void priceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceKeyPressed
        int key=evt.getKeyCode();
        if(key==10)
        {
            String sql ="insert into cardatabase values(?,?,?,?,?,?,?,?,?,?,0,0,null,?,0,0,0)";
        String sql1="insert into selleractivity values(?,?,?,?,?)";

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/loginandregister","root","bms@ise");
            PreparedStatement pstmt =conn.prepareStatement(sql);
            pstmt.setString(1,brand.getText());
            pstmt.setString(2,model.getText());
            pstmt.setString(3,regyear.getText());
            pstmt.setString(4,color.getText());
            pstmt.setString(5,km.getText());
            pstmt.setString(6,location.getText());
            pstmt.setString(7,regno.getText());
            if(variant.getSelectedItem().toString()=="Select Variant")
            {
                JOptionPane.showMessageDialog(null,"Select Variant");
            }
            else
            {
            pstmt.setString(8,variant.getSelectedItem().toString());
            pstmt.setString(9,desc.getText());
            pstmt.setString(10,price.getText());
            pstmt.setString(11,p);
            pstmt.executeUpdate();
            
            PreparedStatement pstmt1 =conn.prepareStatement(sql1);
            pstmt1.setString(1,p);
            pstmt1.setString(2,brand.getText());
            pstmt1.setString(3,model.getText());
            pstmt1.setString(4,regno.getText());
            
            pstmt1.setInt(5,0);
            pstmt1.executeUpdate();
            JOptionPane.showMessageDialog(null,"Congrats Now your car details is on our database");
            new buysell(y,p,e).setVisible(true);
            this.setVisible(false);
            conn.close();
            }
        }

        catch(HeadlessException | ClassNotFoundException | SQLException e){
            String s="com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '"+regno.getText()+"' for key 'PRIMARY'";
            if(e.toString().equals(s))
            {
                JOptionPane.showMessageDialog(null,"The car with the same registration number already exists");
            }
            
            else
            {
            JOptionPane.showMessageDialog(null,"Oops... Something Happened..   Check if you have entered all the Details correctly.");
            }
        }

        
        }
    }//GEN-LAST:event_priceKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new homepage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brand;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JTextField color;
    private javax.swing.JTextField desc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField km;
    private javax.swing.JTextField location;
    private javax.swing.JTextField model;
    private javax.swing.JLabel name1;
    private javax.swing.JTextField price;
    private javax.swing.JTextField regno;
    private javax.swing.JTextField regyear;
    private javax.swing.JComboBox<String> variant;
    // End of variables declaration//GEN-END:variables
}
