/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cars24;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.TextField;
import java.awt.Toolkit;
import java.security.MessageDigest;
import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author hruth
 */
public class Signup extends javax.swing.JFrame {
Toolkit tk = Toolkit.getDefaultToolkit();
int xsize=(int)tk.getScreenSize().getWidth();
int ysize=(int)tk.getScreenSize().getHeight();
String regexemail = "^(.+)@(.+)$";
String regexpno="((\\+*)((0[ -]+)*|(91 )*)(\\d{12}+|\\d{10}+))|\\d{5}([- ]*)\\d{6}";
Pattern patternemail = Pattern.compile(regexemail);
Pattern patternpno=Pattern.compile(regexpno);
String regexpass="^(?=.*?[A-Z])(?=(.*[a-z]){1,})(?=(.*[\\d]){1,})(?=(.*[\\W]){1,})(?!.*\\s).{8,}$";
Pattern patternpass=Pattern.compile(regexpass);

    
    //System.out.println(email +" : "+ matcher.matches());


    @Override
    public void setSize(int width, int height) {
        super.setSize(width, height); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
        jPanel1.setFocusable(true);
        this.setSize(xsize, ysize);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        firstname = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        pno = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        text = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        show = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Back");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(700, 690, 69, 21);

        firstname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        firstname.setForeground(new java.awt.Color(102, 102, 102));
        firstname.setText("   First name");
        firstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnameFocusLost(evt);
            }
        });
        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        firstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                firstnameKeyPressed(evt);
            }
        });
        getContentPane().add(firstname);
        firstname.setBounds(640, 250, 201, 44);

        lastname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lastname.setForeground(new java.awt.Color(102, 102, 102));
        lastname.setText("  Last Name");
        lastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastnameFocusLost(evt);
            }
        });
        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });
        lastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lastnameKeyPressed(evt);
            }
        });
        getContentPane().add(lastname);
        lastname.setBounds(640, 310, 201, 48);

        pno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pno.setForeground(new java.awt.Color(102, 102, 102));
        pno.setText("  Phone No.");
        pno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pnoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pnoFocusLost(evt);
            }
        });
        pno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnoActionPerformed(evt);
            }
        });
        pno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pnoKeyPressed(evt);
            }
        });
        getContentPane().add(pno);
        pno.setBounds(640, 380, 201, 48);

        mail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mail.setForeground(new java.awt.Color(102, 102, 102));
        mail.setText("   E-Mail Id");
        mail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mailFocusLost(evt);
            }
        });
        mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailActionPerformed(evt);
            }
        });
        mail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mailKeyPressed(evt);
            }
        });
        getContentPane().add(mail);
        mail.setBounds(640, 450, 201, 47);

        text.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        text.setForeground(new java.awt.Color(102, 102, 102));
        text.setText("Create Password");
        text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFocusLost(evt);
            }
        });
        text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textMousePressed(evt);
            }
        });
        text.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                textComponentHidden(evt);
            }
        });
        text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textActionPerformed(evt);
            }
        });
        getContentPane().add(text);
        text.setBounds(640, 520, 201, 45);

        pass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passFocusLost(evt);
            }
        });
        pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passMousePressed(evt);
            }
        });
        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passKeyPressed(evt);
            }
        });
        getContentPane().add(pass);
        pass.setBounds(640, 520, 201, 42);

        show.setText("Show Password");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        getContentPane().add(show);
        show.setBounds(640, 570, 111, 21);

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(690, 610, 98, 34);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Already a user?Login");
        jButton2.setAlignmentY(0.0F);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(640, 660, 190, 25);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("SIGNUP");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(670, 160, 160, 65);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars24/1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1560, 860);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 0, 1280, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameFocusGained
        if(lastname.getText().trim().toLowerCase().equals("last name"))
        {
            lastname.setText("");
            lastname.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_lastnameFocusGained

    private void lastnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameFocusLost
        if(lastname.getText().trim().equals("") || lastname.getText().trim().toLowerCase().equals("last name")){
            lastname.setText("   Last Name");
            lastname.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_lastnameFocusLost

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    private void pnoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pnoFocusGained
        if(pno.getText().trim().toLowerCase().equals("phone no."))
        {
            pno.setText("");
            pno.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_pnoFocusGained

    private void pnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pnoFocusLost
        if(pno.getText().trim().equals("") || pno.getText().trim().toLowerCase().equals("phone no.")){
            pno.setText("   Phone no.");
            pno.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_pnoFocusLost

    private void pnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnoActionPerformed

    private void mailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFocusGained
        if(mail.getText().trim().toLowerCase().equals("e-mail id"))
        {
            mail.setText("");
            mail.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_mailFocusGained

    private void mailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFocusLost
        if(mail.getText().trim().equals("") || mail.getText().trim().toLowerCase().equals("e-mail id")){
            mail.setText("   E-mail id");
            mail.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_mailFocusLost

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailActionPerformed

    private void textFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFocusGained
        pass.requestFocus();
    }//GEN-LAST:event_textFocusGained

    private void textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_textFocusLost

    private void textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textActionPerformed

    private void textMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textMousePressed
        pass.requestFocus();
       text.setVisible(false);            // TODO add your handling code here:
    }//GEN-LAST:event_textMousePressed

    private void passMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passMousePressed
        pass.setVisible(true);
       text.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_passMousePressed

    private void firstnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameFocusLost
    if(firstname.getText().trim().equals("") || firstname.getText().trim().toLowerCase().equals("first name")){
            firstname.setText("   First Name");
            firstname.setForeground(new Color(102,102,102));
        }        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameFocusLost

    private void firstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameFocusGained
    if(firstname.getText().trim().toLowerCase().equals("first name"))
        {
            firstname.setText("");
            firstname.setForeground(Color.BLACK);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameFocusGained

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        
    }//GEN-LAST:event_firstnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String sql ="insert into logintable values(?,?,?,?,?)";
      

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/loginandregister","root","bms@ise");
            PreparedStatement pstmt =conn.prepareStatement(sql);
           
            pstmt.setString(1,firstname.getText());
            pstmt.setString(2,lastname.getText());
            pstmt.setString(3,pno.getText());
            Matcher matcher1 = patternpno.matcher(pno.getText());
            if(matcher1.matches())
            {
            pstmt.setString(4,mail.getText());
            Matcher matcher = patternemail.matcher(mail.getText());
            if(matcher.matches())
            {
            if(md5(pass.getPassword()).equals(""))
            {
                JOptionPane.showMessageDialog(null,"cannot encrypt");
                return;
            }
            pstmt.setString(5,md5(pass.getPassword()));
            Matcher matcher2 = patternpass.matcher(new String(pass.getPassword()));
            
            if(matcher2.matches())
            {
            pstmt.executeUpdate();
           
            
            JOptionPane.showMessageDialog(null,"Signup sucessfull. Now you can login using your mobile number");
            conn.close();
            new login().setVisible(true);
            String to = mail.getText();
                String subject = "Car24";
                String message =  "Thank you for signing up with cars24";
                
                String user = "cars24.dbms.java@gmail.com";
                String pass = "dbmsjava";

                SendMail.send(to,subject, message, user, pass); 
            this.setVisible(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Password should contain At least one upper case letter,at least one lower case letter,at least one digit,at least one special character,minimum eight in length");
            }
            }
            else
            {
                JOptionPane.showMessageDialog(null,"enter correct email");
            }
            }
            else
            {
                JOptionPane.showMessageDialog(null,"enter correct Phone number");
            }
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);

        }
    }//GEN-LAST:event_jButton1ActionPerformed
private String md5(char[] c)
        {
            try
            {
                MessageDigest digs=MessageDigest.getInstance("SHA");
                digs.update((new String(c)).getBytes("UTF8"));
                String str=new String(digs.digest());
                return str;
            }
            catch(Exception e)
                    {
                        return "";
                    }
        }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void firstnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstnameKeyPressed
        int key=evt.getKeyCode();
        if(key==10)
        {
            lastname.requestFocus();
        }
    }//GEN-LAST:event_firstnameKeyPressed

    private void pnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnoKeyPressed
        int key=evt.getKeyCode();
        if(key==10)
        {
            mail.requestFocus();
        }
    }//GEN-LAST:event_pnoKeyPressed

    private void lastnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastnameKeyPressed
        int key=evt.getKeyCode();
        if(key==10)
        {
            pno.requestFocus();
        }
    }//GEN-LAST:event_lastnameKeyPressed

    private void mailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mailKeyPressed
        int key=evt.getKeyCode();
        if(key==10)
        {
            pass.requestFocus();
        }
        
    }//GEN-LAST:event_mailKeyPressed

    private void passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyPressed
        int key=evt.getKeyCode();
        if(key==10)
        {
           String sql ="insert into logintable values(?,?,?,?,?)";
      

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/loginandregister","root","bms@ise");
            PreparedStatement pstmt =conn.prepareStatement(sql);
           
            pstmt.setString(1,firstname.getText());
            pstmt.setString(2,lastname.getText());
            pstmt.setString(3,pno.getText());
            Matcher matcher1 = patternpno.matcher(pno.getText());
            if(matcher1.matches())
            {
            pstmt.setString(4,mail.getText());
            Matcher matcher = patternemail.matcher(mail.getText());
            if(matcher.matches())
            {
            if(md5(pass.getPassword()).equals(""))
            {
                JOptionPane.showMessageDialog(null,"cannot encrypt");
                return;
            }
            pstmt.setString(5,md5(pass.getPassword()));
            Matcher matcher2 = patternpass.matcher(new String(pass.getPassword()));
            
            if(matcher2.matches())
            {
            pstmt.executeUpdate();
           
            
            JOptionPane.showMessageDialog(null,"Signup sucessfull. Now you can login using your mobile number");
            conn.close();
            new login().setVisible(true);
                String to = mail.getText();
                String subject = "Car24";
                String message =  "Thank you for signing up with cars24";
                
                String user = "cars24.dbms.java@gmail.com";
                String pass = "dbmsjava";

                SendMail.send(to,subject, message, user, pass); 
            this.setVisible(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Password should contain At least one upper case letter,at least one lower case letter,at least one digit,at least one special character,minimum eight in length");
            }
            }
            else
            {
                JOptionPane.showMessageDialog(null,"enter correct email");
            }
            }
            else
            {
                JOptionPane.showMessageDialog(null,"enter correct Phone number");
            }
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);

        }
        }
    }//GEN-LAST:event_passKeyPressed

    private void passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocusGained
        text.setVisible(false);
    }//GEN-LAST:event_passFocusGained

    private void passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocusLost
        
    }//GEN-LAST:event_passFocusLost

    private void textComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_textComponentHidden
        pass.requestFocus();
    }//GEN-LAST:event_textComponentHidden

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        if(show.isSelected())
        {
            pass.setEchoChar((char)0);
        }
        else
        {
            pass.setEchoChar('*');
        }
    }//GEN-LAST:event_showActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new homepage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField firstname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField mail;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField pno;
    private javax.swing.JCheckBox show;
    private javax.swing.JTextField text;
    // End of variables declaration//GEN-END:variables
}
