/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cars24;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author hruth
 */
public class view extends javax.swing.JFrame {
String p;
String z;
String y;
String s;
String e;
Toolkit tk = Toolkit.getDefaultToolkit();
int xsize=(int)tk.getScreenSize().getWidth();
int ysize=(int)tk.getScreenSize().getHeight();


    @Override
    public void setSize(int width, int height) {
        super.setSize(width, height); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form buyer
     */
    
    public view() {
        initComponents();
        jPanel1.setFocusable(true);
    }
    public view(String x,String m,String e1) 
    {
       initComponents();
        jPanel1.setFocusable(true);
        p=m;
        y=x;
        z="Hey, "+x;
        name1.setText(z);
        this.setSize(xsize, ysize);
        e=e1;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        name1 = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        accept = new javax.swing.JButton();
        reg1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        reject = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(446, 543));
        jPanel1.setLayout(null);

        search.setBackground(new java.awt.Color(0, 153, 255));
        search.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search your car");
        search.setBorder(null);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search);
        search.setBounds(610, 210, 156, 40);

        tab.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tab.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(580, 270, 533, 126);

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setText("Logout");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(1340, 170, 73, 36);

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(780, 590, 139, 36);

        name1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(name1);
        name1.setBounds(1090, 90, 280, 60);

        price.setBackground(new java.awt.Color(255, 255, 255));
        price.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        price.setOpaque(true);
        jPanel1.add(price);
        price.setBounds(940, 430, 136, 42);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Reg no.");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(770, 480, 60, 23);

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        name.setOpaque(true);
        jPanel1.add(name);
        name.setBounds(590, 430, 111, 41);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Assigned Price");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(960, 480, 100, 23);

        accept.setBackground(new java.awt.Color(0, 153, 255));
        accept.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        accept.setForeground(new java.awt.Color(255, 255, 255));
        accept.setText("Accept the price");
        accept.setBorder(null);
        accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptActionPerformed(evt);
            }
        });
        jPanel1.add(accept);
        accept.setBounds(660, 520, 139, 36);

        reg1.setBackground(new java.awt.Color(255, 255, 255));
        reg1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        reg1.setOpaque(true);
        jPanel1.add(reg1);
        reg1.setBounds(740, 430, 160, 41);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Brand");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(590, 480, 49, 23);

        reject.setBackground(new java.awt.Color(0, 153, 255));
        reject.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        reject.setForeground(new java.awt.Color(255, 255, 255));
        reject.setText("Reject the price");
        reject.setBorder(null);
        reject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectActionPerformed(evt);
            }
        });
        jPanel1.add(reject);
        reject.setBounds(890, 520, 139, 36);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("* 0 in price column means price is not assigned yet");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(580, 400, 393, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cars24/1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1570, 870);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -4, 1570, 870);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectActionPerformed
        String sql ="delete from cardatabase where regno=?";
        String sql1="delete from selleractivity where regno=?";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/loginandregister","root","bms@ise");
            PreparedStatement pstmt =conn.prepareStatement(sql);
            if(Integer.parseInt(price.getText())!=0)
            {
            pstmt.setString(1,reg1.getText());

            pstmt.executeUpdate();

            PreparedStatement pstmt1 =conn.prepareStatement(sql1);

            pstmt1.setString(1,reg1.getText());

            pstmt1.executeUpdate();
            JOptionPane.showMessageDialog(null,"We regret that you are not happy with our price");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Price is not assigned yet");
            }
            conn.close();
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);

        }
    }//GEN-LAST:event_rejectActionPerformed

    private void acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptActionPerformed
        String sql ="update cardatabase set accept=1 where regno=?";
        
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/loginandregister","root","bms@ise");
            PreparedStatement pstmt =conn.prepareStatement(sql);
            if(Integer.parseInt(price.getText())!=0)
            {
            pstmt.setString(1,reg1.getText());
            
            
            pstmt.executeUpdate();

            JOptionPane.showMessageDialog(null,"Thank you for selling your car");
            new sellerdetails(y,p,e).setVisible(true);
            this.setVisible(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Price is not assigned yet");
            }
            
            conn.close();
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);

        }
    }//GEN-LAST:event_acceptActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new buysell(y,p,e).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMouseClicked
        DefaultTableModel model = (DefaultTableModel)tab.getModel();

        int selectedRowIndex = tab.getSelectedRow();

        reg1.setText(model.getValueAt(selectedRowIndex, 2).toString());
        name.setText(model.getValueAt(selectedRowIndex, 0).toString());
        price.setText(model.getValueAt(selectedRowIndex, 3).toString());
    }//GEN-LAST:event_tabMouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/loginandregister","root","bms@ise");
            String sql="select brand,model,regno,price from selleractivity where pno= ? ";

            PreparedStatement pstmt =conn.prepareStatement(sql);
            pstmt.setString(1,p);

            ResultSet rs = pstmt.executeQuery();
            tab.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_searchActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new homepage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accept;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel price;
    private javax.swing.JLabel reg1;
    private javax.swing.JButton reject;
    private javax.swing.JButton search;
    private javax.swing.JTable tab;
    // End of variables declaration//GEN-END:variables
}
